/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    CartComp: typeof import('./views/Cart/CartComp.vue')['default']
    DetailsComp: typeof import('./views/Details/DetailsComp.vue')['default']
    ErrorComp: typeof import('./views/NotFound/ErrorComp.vue')['default']
    FooterComp: typeof import('./components/Footer/FooterComp.vue')['default']
    GoodslistComp: typeof import('./components/GoodsList/GoodslistComp.vue')['default']
    GridComp: typeof import('./views/Home/components/GridComp.vue')['default']
    HeaderComp: typeof import('./components/Header/HeaderComp.vue')['default']
    HomeComp: typeof import('./views/Home/HomeComp.vue')['default']
    ListComp: typeof import('./views/List/ListComp.vue')['default']
    LoginComp: typeof import('./views/Login/LoginComp.vue')['default']
    MainComp: typeof import('./views/Main/MainComp.vue')['default']
    MineComp: typeof import('./views/Mine/MineComp.vue')['default']
    RegisterComp1: typeof import('./views/Register/RegisterComp-1.vue')['default']
    RegisterComp2: typeof import('./views/Register/RegisterComp-2.vue')['default']
    RegisterComp3: typeof import('./views/Register/RegisterComp-3.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwiperComp: typeof import('./views/Home/components/SwiperComp.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDialog: typeof import('vant/es')['Dialog']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNotify: typeof import('vant/es')['Notify']
    VanSearch: typeof import('vant/es')['Search']
    VanSubmitBar: typeof import('vant/es')['SubmitBar']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
    VanToast: typeof import('vant/es')['Toast']
  }
}
